name: Backend Integration Tests

on: [pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: |
        cd backend/
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up MongoDB Database
      run: |
        docker run --network host mongo mongo --eval 'use ucla_swipes_exchange' --host localhost
        docker run --network host mongo mongo --eval 'db.createCollection("user")' --host localhost

    - name: Run Integration Tests
      run: |
        cd backend/tests/
        chmod +x run_test.sh
        ./run_test.sh

    - name: Clean up
      if: always()
      run: |
        # Any cleanup steps if needed
