name: Flask CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd backend/
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask application
      run: |
        cd backend/
        FLASK_APP=app.py FLASK_ENV=development python -m flask run --host=0.0.0.0 --port=5000 &> flask.log &
        echo "FLASK_PID=$!" >> $GITHUB_ENV

    - name: Wait for Flask to start
      run: sleep 10

    - name: Check Flask server is running
      run: curl --fail http://127.0.0.1:5000/ || exit 1

    - name: Shutdown Flask server
      if: always()
      run: |
        kill $FLASK_PID || true
