name: Backend Integration Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '4.4'

    - name: Install dependencies
      run: |
        cd backend/
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up MongoDB Database
      run: |
        # Connect to MongoDB and create database and collection
        docker run --network host --rm mongo:4.4 mongo --eval 'db.createCollection("user")' --host localhost ucla_swipes_exchange

    - name: Run Integration Tests
      run: |
        cd backend/tests/
        chmod +x run_test.sh
        ./run_test.sh
